# Generated by Django 4.1.3 on 2022-12-03 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='ClientesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=100)),
                ('dni', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='OrdenesModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observacion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.clientesmodel')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ordenes',
            },
        ),
        migrations.CreateModel(
            name='ProductosModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('marca', models.CharField(max_length=45)),
                ('talla', models.CharField(max_length=45)),
                ('codigo', models.CharField(max_length=45)),
                ('imagen', models.TextField()),
                ('precio', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.categoriasmodel')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='PagosModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
                ('orden_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.ordenesmodel')),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='DetallesOrdenModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('orden_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.ordenesmodel')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.productosmodel')),
            ],
            options={
                'db_table': 'ordenes_detalle',
            },
        ),
        migrations.CreateModel(
            name='BoletasPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=45)),
                ('total', models.FloatField()),
                ('estado', models.BooleanField(default=True)),
                ('pago_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.pagosmodel')),
            ],
            options={
                'db_table': 'botelas_pago',
            },
        ),
    ]
